[{"name": "test.test_diamond.Diamond.test_calls", "status": "failed", "message": "Expected 'eye' to have been called.", "passed": false, "points": ["p02-13.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e13_diamond/test/test_diamond.py\", line 64, in test_calls\n    peye.assert_called()\n", "  File \"/usr/lib/python3.10/unittest/mock.py\", line 888, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_diamond.Diamond.test_content", "status": "failed", "message": "0.0 != 1 : Incorrect number of 1s for call 'diamond(1)'!", "passed": false, "points": ["p02-13.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e13_diamond/test/test_diamond.py\", line 57, in test_content\n    self.assertEqual(np.sum(d), size,\n"]}, {"name": "test.test_diamond.Diamond.test_shape", "status": "failed", "message": "Tuples differ: (0,) != (1, 1)\n\nFirst differing element 0:\n0\n1\n\nSecond tuple contains 1 additional elements.\nFirst extra element 1:\n1\n\n- (0,)\n+ (1, 1) : Incorrect shape for call 'diamond(1)'!", "passed": false, "points": ["p02-13.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e13_diamond/test/test_diamond.py\", line 47, in test_shape\n    self.assertEqual(d.shape, correct_shape,\n"]}, {"name": "test.test_diamond.Diamond.test_type", "status": "failed", "message": "dtype('float64') != <class 'int'> : Incorrect element type!", "passed": false, "points": ["p02-13.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e13_diamond/test/test_diamond.py\", line 41, in test_type\n    self.assertEqual(d.dtype, int, msg=\"Incorrect element type!\")\n"]}]