[{"name": "test.test_rational.RationalTest.test_comparison", "status": "errored", "message": "Rational() takes no arguments", "passed": false, "points": ["p02-09.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e09_rational/test/test_rational.py\", line 42, in test_comparison\n    r1=Rational(1,4)\n"]}, {"name": "test.test_rational.RationalTest.test_plusminus", "status": "errored", "message": "Rational() takes no arguments", "passed": false, "points": ["p02-09.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e09_rational/test/test_rational.py\", line 36, in test_plusminus\n    r1=Rational(1,4)\n"]}, {"name": "test.test_rational.RationalTest.test_print", "status": "errored", "message": "Rational() takes no arguments", "passed": false, "points": ["p02-09.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e09_rational/test/test_rational.py\", line 18, in test_print\n    r1=Rational(1,4)\n"]}, {"name": "test.test_rational.RationalTest.test_proddiv", "status": "errored", "message": "Rational() takes no arguments", "passed": false, "points": ["p02-09.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e09_rational/test/test_rational.py\", line 30, in test_proddiv\n    r1=Rational(1,4)\n"]}]