[{"name": "test.test_regression.Regression.test_00_imports", "status": "passed", "message": "", "passed": true, "points": ["p08-01.0"], "backtrace": []}, {"name": "test.test_regression.Regression.test_01_load", "status": "passed", "message": "", "passed": true, "points": ["p08-01.1"], "backtrace": []}, {"name": "test.test_regression.Regression.test_02_rescale", "status": "passed", "message": "", "passed": true, "points": ["p08-01.2"], "backtrace": []}, {"name": "test.test_regression.Regression.test_03_rescaled_variables", "status": "passed", "message": "", "passed": true, "points": ["p08-01.3"], "backtrace": []}, {"name": "test.test_regression.Regression.test_04_sbp1", "status": "passed", "message": "", "passed": true, "points": ["p08-01.4"], "backtrace": []}, {"name": "test.test_regression.Regression.test_05_sbp_with_age", "status": "passed", "message": "", "passed": true, "points": ["p08-01.5"], "backtrace": []}, {"name": "test.test_regression.Regression.test_06_sbp_with_interactions", "status": "passed", "message": "", "passed": true, "points": ["p08-01.6"], "backtrace": []}, {"name": "test.test_regression.Regression.test_07_sbp_with_interactions_visualization", "status": "passed", "message": "", "passed": true, "points": ["p08-01.7"], "backtrace": []}, {"name": "test.test_regression.Regression.test_08_sbp_with_cigarets", "status": "passed", "message": "", "passed": true, "points": ["p08-01.8"], "backtrace": []}, {"name": "test.test_regression.Regression.test_09_high_blood_pressure", "status": "passed", "message": "", "passed": true, "points": ["p08-01.9"], "backtrace": []}, {"name": "test.test_regression.Regression.test_10_high_blood_pressure2", "status": "passed", "message": "", "passed": true, "points": ["p08-01.10"], "backtrace": []}, {"name": "test.test_regression.Regression.test_11_high_blood_pressure3", "status": "failed", "message": "3 != 6 : Expected plot method to be called six times!", "passed": false, "points": ["p08-01.11"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 272, in test_11_high_blood_pressure3\n    self.assertEqual(plot_method.mock.call_count, 6,\n"]}, {"name": "test.test_regression.Regression.test_12_train_test_split", "status": "failed", "message": "False is not true : Could not find function 'train_test_split' {'self': <test.test_regression.Regression testMethod=test_12_train_test_split>, 'orig':           0         1         2         3         4         5         6         7         8         9\n0  0.166261  3.097491  0.993713  0.176389 -0.178886  0.441134 -0.071579 -0.999021 -1.979111 -0.194594\n1 -0.092262 -1.187371  1.023620  1.308613 -0.332693  0.138013  1.257135  0.957167 -0.870900 -0.290776\n2  0.054059  0.263642  0.099425 -1.170405 -0.142494  1.650627 -2.064422  0.929976  0.093217 -1.329847\n3 -0.611412  0.593341  0.167431 -1.911849 -0.599336  1.243573 -1.367456  1.848114 -1.820851 -1.363171\n4  0.181931 -0.318945  0.700817  0.654257 -0.511301  2.018622  0.264663  0.725363  0.506542 -1.160971\n5 -0.159233 -0.497821  0.543671  1.656887  0.915190 -0.108910 -0.230730  0.068137 -1.290778  0.194358\n6 -0.453204  1.237438 -1.071492  0.258850 -0.613574 -0.290927 -1.297413 -0.227890  0.621395  0.400409\n7  1.019777 -0.766929  0.345008  0.993031 -0.312684 -0.364247  0.645652 -0.757890  0.905563 -0.869932\n8  0.130291 -0.131168 -0.302294 -0.919052 -0.666786 -1.072479  0.648978  0.299085  0.741543 -1.138909\n9  0.146712 -0.874708 -0.559226 -1.198968  0.085409 -2.294891 -0.179640  0.338098 -0.777966  0.015214, 'df':           0         1         2         3         4         5         6         7         8         9\n0  0.166261  3.097491  0.993713  0.176389 -0.178886  0.441134 -0.071579 -0.999021 -1.979111 -0.194594\n1 -0.092262 -1.187371  1.023620  1.308613 -0.332693  0.138013  1.257135  0.957167 -0.870900 -0.290776\n2  0.054059  0.263642  0.099425 -1.170405 -0.142494  1.650627 -2.064422  0.929976  0.093217 -1.329847\n3 -0.611412  0.593341  0.167431 -1.911849 -0.599336  1.243573 -1.367456  1.848114 -1.820851 -1.363171\n4  0.181931 -0.318945  0.700817  0.654257 -0.511301  2.018622  0.264663  0.725363  0.506542 -1.160971\n5 -0.159233 -0.497821  0.543671  1.656887  0.915190 -0.108910 -0.230730  0.068137 -1.290778  0.194358\n6 -0.453204  1.237438 -1.071492  0.258850 -0.613574 -0.290927 -1.297413 -0.227890  0.621395  0.400409\n7  1.019777 -0.766929  0.345008  0.993031 -0.312684 -0.364247  0.645652 -0.757890  0.905563 -0.869932\n8  0.130291 -0.131168 -0.302294 -0.919052 -0.666786 -1.072479  0.648978  0.299085  0.741543 -1.138909\n9  0.146712 -0.874708 -0.559226 -1.198968  0.085409 -2.294891 -0.179640  0.338098 -0.777966  0.015214, 'pd': <module 'pandas' from '/home/sonya/.local/lib/python3.10/site-packages/pandas/__init__.py'>, 'np': <module 'numpy' from '/home/sonya/.local/lib/python3.10/site-packages/numpy/__init__.py'>, 'plt': <module 'matplotlib.pyplot' from '/home/sonya/.local/lib/python3.10/site-packages/matplotlib/pyplot.py'>, 'statsmodels': <module 'statsmodels' from '/home/sonya/.local/lib/python3.10/site-packages/statsmodels/__init__.py'>, 'sm': <module 'statsmodels.api' from '/home/sonya/.local/lib/python3.10/site-packages/statsmodels/api.py'>, 'smf': <module 'statsmodels.formula.api' from '/home/sonya/.local/lib/python3.10/site-packages/statsmodels/formula/api.py'>, 'abline_plot': <function abline_plot at 0x7f91f6187c70>}, # exercise 12\n# Put your solution here!!", "passed": false, "points": ["p08-01.12"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 289, in test_12_train_test_split\n    self.assertTrue(\"train_test_split\" in locals(),\n"]}, {"name": "test.test_regression.Regression.test_13_cross_validation", "status": "failed", "message": "'error_model' not found in {'self': <test.test_regression.Regression testMethod=test_13_cross_validation>, 'pd': <module 'pandas' from '/home/sonya/.local/lib/python3.10/site-packages/pandas/__init__.py'>, 'np': <module 'numpy' from '/home/sonya/.local/lib/python3.10/site-packages/numpy/__init__.py'>, 'plt': <module 'matplotlib.pyplot' from '/home/sonya/.local/lib/python3.10/site-packages/matplotlib/pyplot.py'>, 'statsmodels': <module 'statsmodels' from '/home/sonya/.local/lib/python3.10/site-packages/statsmodels/__init__.py'>, 'sm': <module 'statsmodels.api' from '/home/sonya/.local/lib/python3.10/site-packages/statsmodels/api.py'>, 'smf': <module 'statsmodels.formula.api' from '/home/sonya/.local/lib/python3.10/site-packages/statsmodels/formula/api.py'>, 'abline_plot': <function abline_plot at 0x7f91f6187c70>, 'get_path': <function get_path at 0x7f91f1dd53f0>, 'fram':         ID     SEX  AGE  FRW  SBP  SBP10  DBP  CHOL  CIG  CHD YRS_CHD  ...      sAGE      sFRW      sSBP      sDBP     sCHOL      sCIG      sCHD    sDEATH  sYRS_DTH  HIGH_BP  PRED_HIGH_BP\n0     4988  female   57  135  186    NaN  120   150    0    1     pre  ...  0.477764  0.834668  0.676501  1.049625 -0.914016 -0.346569 -0.035923  0.827181 -0.665514        1             1\n1     3001  female   60  123  165    NaN  100   167   25    0      16  ...  0.791473  0.496687  0.301796  0.346698 -0.730446  0.732493 -0.227056  1.295472  0.099516        1             1\n2     5079  female   54  115  140    NaN   90   213    5    0       8  ...  0.164056  0.271367 -0.144281 -0.004765 -0.233727 -0.130757 -0.227056  0.983278 -0.410504        1             1\n3     5162  female   52  102  170    NaN  104   280   15    0      10  ... -0.045083 -0.094779  0.391012  0.487283  0.489755  0.300868 -0.227056  0.827181 -0.665514        1             1\n4     4672  female   45   99  185    NaN  105   326   20    0       8  ... -0.777070 -0.179274  0.658658  0.522430  0.986475  0.516680 -0.227056  1.295472  0.099516        1             1\n...    ...     ...  ...  ...  ...    ...  ...   ...  ...  ...     ...  ...       ...       ...       ...       ...       ...       ...       ...       ...       ...      ...           ...\n1389  4132    male   51  100  160    NaN   98   216   30    0      10  ... -0.149653 -0.151109  0.212581  0.276405 -0.201332  0.948305 -0.227056  0.827181 -0.665514        1             1\n1390  5418    male   50   95  174    NaN  106   192    5    0       8  ... -0.254223 -0.291935  0.462384  0.557576 -0.460490 -0.130757 -0.227056  0.983278 -0.410504        1             1\n1391  6260    male   57   88  144    NaN   96   184   20    0       2  ...  0.477764 -0.489090 -0.072908  0.206113 -0.546876  0.516680 -0.227056  0.202792 -1.685555        1             0\n1392  5786    male   62   87  156    NaN   90   255    0    0       6  ...  1.000612 -0.517255  0.141209 -0.004765  0.219799 -0.346569 -0.227056  0.514986 -1.175534        1             0\n1393  6071    male   45   83  156    NaN   90   255   15    0       6  ... -0.777070 -0.629916  0.141209 -0.004765  0.219799  0.300868 -0.227056  0.514986 -1.175534        1             0\n\n[1394 rows x 25 columns], 'rescale': <function rescale at 0x7f91f1dd55a0>, 'fit': <statsmodels.genmod.generalized_linear_model.GLMResultsWrapper object at 0x7f91f1ea8760>, 'error_rate_orig': 0.35581061692969873} : Could not find variable 'error_model'!", "passed": false, "points": ["p08-01.13"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 315, in test_13_cross_validation\n    self.assertIn(\"error_model\", locals(), msg=\"Could not find variable 'error_model'!\")\n"]}, {"name": "test.test_regression.Regression.test_14_chd", "status": "failed", "message": "'hasCHD' not found in Index(['ID', 'SEX', 'AGE', 'FRW', 'SBP', 'SBP10', 'DBP', 'CHOL', 'CIG', 'CHD',\n       'YRS_CHD', 'DEATH', 'YRS_DTH', 'CAUSE', 'sAGE', 'sFRW', 'sSBP', 'sDBP',\n       'sCHOL', 'sCIG', 'sCHD', 'sDEATH', 'sYRS_DTH'],\n      dtype='object') : No variable hasCHD in DataFrame 'fram'!", "passed": false, "points": ["p08-01.14"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 332, in test_14_chd\n    self.assertIn(\"hasCHD\", myfram.columns, msg=\"No variable hasCHD in DataFrame 'fram'!\")\n"]}, {"name": "test.test_regression.Regression.test_15_chd2", "status": "errored", "message": "'fit'", "passed": false, "points": ["p08-01.15"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 346, in test_15_chd2\n    myfit = locals()[\"fit\"]\n"]}, {"name": "test.test_regression.Regression.test_16_chd_visualization", "status": "failed", "message": "Expected 'scatter' to have been called.", "passed": false, "points": ["p08-01.16"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 368, in test_16_chd_visualization\n    pltscatter.assert_called()\n", "  File \"/usr/lib/python3.10/unittest/mock.py\", line 888, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_regression.Regression.test_17_chd_prediction", "status": "failed", "message": "False is not true : Could not find variable 'point'!", "passed": false, "points": ["p08-01.17"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 381, in test_17_chd_prediction\n    self.assertTrue(\"point\" in locals(), msg=\"Could not find variable 'point'!\")\n"]}]