[{"name": "test.test_regression.Regression.test_00_imports", "status": "passed", "message": "", "passed": true, "points": ["p08-01.0"], "backtrace": []}, {"name": "test.test_regression.Regression.test_01_load", "status": "passed", "message": "", "passed": true, "points": ["p08-01.1"], "backtrace": []}, {"name": "test.test_regression.Regression.test_02_rescale", "status": "passed", "message": "", "passed": true, "points": ["p08-01.2"], "backtrace": []}, {"name": "test.test_regression.Regression.test_03_rescaled_variables", "status": "passed", "message": "", "passed": true, "points": ["p08-01.3"], "backtrace": []}, {"name": "test.test_regression.Regression.test_04_sbp1", "status": "passed", "message": "", "passed": true, "points": ["p08-01.4"], "backtrace": []}, {"name": "test.test_regression.Regression.test_05_sbp_with_age", "status": "passed", "message": "", "passed": true, "points": ["p08-01.5"], "backtrace": []}, {"name": "test.test_regression.Regression.test_06_sbp_with_interactions", "status": "passed", "message": "", "passed": true, "points": ["p08-01.6"], "backtrace": []}, {"name": "test.test_regression.Regression.test_07_sbp_with_interactions_visualization", "status": "passed", "message": "", "passed": true, "points": ["p08-01.7"], "backtrace": []}, {"name": "test.test_regression.Regression.test_08_sbp_with_cigarets", "status": "errored", "message": "'fit'", "passed": false, "points": ["p08-01.8"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 201, in test_08_sbp_with_cigarets\n    myfit = locals()[\"fit\"]\n"]}, {"name": "test.test_regression.Regression.test_09_high_blood_pressure", "status": "errored", "message": "'fit'", "passed": false, "points": ["p08-01.9"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 225, in test_09_high_blood_pressure\n    myfit = locals()[\"fit\"]\n"]}, {"name": "test.test_regression.Regression.test_10_high_blood_pressure2", "status": "errored", "message": "'fit'", "passed": false, "points": ["p08-01.10"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 243, in test_10_high_blood_pressure2\n    myfit = locals()[\"fit\"]\n"]}, {"name": "test.test_regression.Regression.test_11_high_blood_pressure3", "status": "failed", "message": "Expected 'subplots' to have been called.", "passed": false, "points": ["p08-01.11"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 269, in test_11_high_blood_pressure3\n    psubplots.assert_called()\n", "  File \"/usr/lib/python3.10/unittest/mock.py\", line 888, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_regression.Regression.test_12_train_test_split", "status": "failed", "message": "False is not true : Could not find function 'train_test_split' {'self': <test.test_regression.Regression testMethod=test_12_train_test_split>, 'orig':           0         1         2         3         4         5         6         7         8         9\n0 -0.548437 -1.606196 -0.210980 -1.072828 -1.068456  0.660775 -1.555248 -1.846413 -0.370239  1.354044\n1  0.130872  0.186720  0.264318  0.410665  2.569056 -0.557132 -0.196876  0.331209 -1.068585  0.906628\n2  0.170155 -0.591175  2.026924  0.160602  1.738630 -1.919438 -0.176971  1.623905  0.091360 -1.672940\n3 -0.221214  0.425382  0.617368 -0.699013 -0.230034  0.184080  0.086259 -1.931489  0.422047  0.586108\n4 -1.345550 -0.197199 -1.324968  0.060470  0.018515 -0.742478 -0.011311 -1.577927 -0.849026 -0.343993\n5  1.818978  3.555688 -1.001163  0.266816  1.440381 -0.475416 -0.155832  0.048153  0.197448 -0.207006\n6  0.162725 -0.424332 -0.404022  0.786722 -0.777314 -1.565440 -0.704662 -0.194858 -0.891252 -0.053741\n7  0.890564  0.343571 -0.273466  1.069780 -0.629066 -0.094131 -2.029226 -0.091729 -1.812768 -0.290442\n8 -0.396561 -0.601991  0.625992  0.946117  0.118397  0.526527  0.038516  1.829667 -0.012353 -1.015301\n9  1.696785  0.048071 -1.078825 -0.008662  0.606855  1.383912 -1.422144 -0.721940  0.781719 -0.106461, 'df':           0         1         2         3         4         5         6         7         8         9\n0 -0.548437 -1.606196 -0.210980 -1.072828 -1.068456  0.660775 -1.555248 -1.846413 -0.370239  1.354044\n1  0.130872  0.186720  0.264318  0.410665  2.569056 -0.557132 -0.196876  0.331209 -1.068585  0.906628\n2  0.170155 -0.591175  2.026924  0.160602  1.738630 -1.919438 -0.176971  1.623905  0.091360 -1.672940\n3 -0.221214  0.425382  0.617368 -0.699013 -0.230034  0.184080  0.086259 -1.931489  0.422047  0.586108\n4 -1.345550 -0.197199 -1.324968  0.060470  0.018515 -0.742478 -0.011311 -1.577927 -0.849026 -0.343993\n5  1.818978  3.555688 -1.001163  0.266816  1.440381 -0.475416 -0.155832  0.048153  0.197448 -0.207006\n6  0.162725 -0.424332 -0.404022  0.786722 -0.777314 -1.565440 -0.704662 -0.194858 -0.891252 -0.053741\n7  0.890564  0.343571 -0.273466  1.069780 -0.629066 -0.094131 -2.029226 -0.091729 -1.812768 -0.290442\n8 -0.396561 -0.601991  0.625992  0.946117  0.118397  0.526527  0.038516  1.829667 -0.012353 -1.015301\n9  1.696785  0.048071 -1.078825 -0.008662  0.606855  1.383912 -1.422144 -0.721940  0.781719 -0.106461, 'pd': <module 'pandas' from '/home/sonya/.local/lib/python3.10/site-packages/pandas/__init__.py'>, 'np': <module 'numpy' from '/home/sonya/.local/lib/python3.10/site-packages/numpy/__init__.py'>, 'plt': <module 'matplotlib.pyplot' from '/home/sonya/.local/lib/python3.10/site-packages/matplotlib/pyplot.py'>, 'statsmodels': <module 'statsmodels' from '/home/sonya/.local/lib/python3.10/site-packages/statsmodels/__init__.py'>, 'smf': <module 'statsmodels.formula.api' from '/home/sonya/.local/lib/python3.10/site-packages/statsmodels/formula/api.py'>, 'abline_plot': <function abline_plot at 0x7f7267065ea0>}, # exercise 12\n# Put your solution here!!", "passed": false, "points": ["p08-01.12"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 289, in test_12_train_test_split\n    self.assertTrue(\"train_test_split\" in locals(),\n"]}, {"name": "test.test_regression.Regression.test_13_cross_validation", "status": "failed", "message": "'error_model' not found in {'self': <test.test_regression.Regression testMethod=test_13_cross_validation>, 'pd': <module 'pandas' from '/home/sonya/.local/lib/python3.10/site-packages/pandas/__init__.py'>, 'np': <module 'numpy' from '/home/sonya/.local/lib/python3.10/site-packages/numpy/__init__.py'>, 'plt': <module 'matplotlib.pyplot' from '/home/sonya/.local/lib/python3.10/site-packages/matplotlib/pyplot.py'>, 'statsmodels': <module 'statsmodels' from '/home/sonya/.local/lib/python3.10/site-packages/statsmodels/__init__.py'>, 'smf': <module 'statsmodels.formula.api' from '/home/sonya/.local/lib/python3.10/site-packages/statsmodels/formula/api.py'>, 'abline_plot': <function abline_plot at 0x7f7267065ea0>, 'get_path': <function get_path at 0x7f7263ac1630>, 'fram':         ID     SEX  AGE  FRW  SBP  SBP10  DBP  CHOL  CIG  CHD YRS_CHD  DEATH  YRS_DTH    CAUSE      sAGE      sFRW      sSBP      sDBP     sCHOL      sCIG      sCHD    sDEATH  sYRS_DTH\n0     4988  female   57  135  186    NaN  120   150    0    1     pre      7       11  unknown  0.477764  0.834668  0.676501  1.049625 -0.914016 -0.346569 -0.035923  0.827181 -0.665514\n1     3001  female   60  123  165    NaN  100   167   25    0      16     10       17  unknown  0.791473  0.496687  0.301796  0.346698 -0.730446  0.732493 -0.227056  1.295472  0.099516\n2     5079  female   54  115  140    NaN   90   213    5    0       8      8       13  unknown  0.164056  0.271367 -0.144281 -0.004765 -0.233727 -0.130757 -0.227056  0.983278 -0.410504\n3     5162  female   52  102  170    NaN  104   280   15    0      10      7       11  unknown -0.045083 -0.094779  0.391012  0.487283  0.489755  0.300868 -0.227056  0.827181 -0.665514\n4     4672  female   45   99  185    NaN  105   326   20    0       8     10       17  unknown -0.777070 -0.179274  0.658658  0.522430  0.986475  0.516680 -0.227056  1.295472  0.099516\n...    ...     ...  ...  ...  ...    ...  ...   ...  ...  ...     ...    ...      ...      ...       ...       ...       ...       ...       ...       ...       ...       ...       ...\n1389  4132    male   51  100  160    NaN   98   216   30    0      10      7       11   stroke -0.149653 -0.151109  0.212581  0.276405 -0.201332  0.948305 -0.227056  0.827181 -0.665514\n1390  5418    male   50   95  174    NaN  106   192    5    0       8      8       13   stroke -0.254223 -0.291935  0.462384  0.557576 -0.460490 -0.130757 -0.227056  0.983278 -0.410504\n1391  6260    male   57   88  144    NaN   96   184   20    0       2      3        3   stroke  0.477764 -0.489090 -0.072908  0.206113 -0.546876  0.516680 -0.227056  0.202792 -1.685555\n1392  5786    male   62   87  156    NaN   90   255    0    0       6      5        7   stroke  1.000612 -0.517255  0.141209 -0.004765  0.219799 -0.346569 -0.227056  0.514986 -1.175534\n1393  6071    male   45   83  156    NaN   90   255   15    0       6      5        7   stroke -0.777070 -0.629916  0.141209 -0.004765  0.219799  0.300868 -0.227056  0.514986 -1.175534\n\n[1394 rows x 23 columns], 'rescale': <function rescale at 0x7f7263ac1750>} : Could not find variable 'error_model'!", "passed": false, "points": ["p08-01.13"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 315, in test_13_cross_validation\n    self.assertIn(\"error_model\", locals(), msg=\"Could not find variable 'error_model'!\")\n"]}, {"name": "test.test_regression.Regression.test_14_chd", "status": "failed", "message": "'hasCHD' not found in Index(['ID', 'SEX', 'AGE', 'FRW', 'SBP', 'SBP10', 'DBP', 'CHOL', 'CIG', 'CHD',\n       'YRS_CHD', 'DEATH', 'YRS_DTH', 'CAUSE', 'sAGE', 'sFRW', 'sSBP', 'sDBP',\n       'sCHOL', 'sCIG', 'sCHD', 'sDEATH', 'sYRS_DTH'],\n      dtype='object') : No variable hasCHD in DataFrame 'fram'!", "passed": false, "points": ["p08-01.14"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 332, in test_14_chd\n    self.assertIn(\"hasCHD\", myfram.columns, msg=\"No variable hasCHD in DataFrame 'fram'!\")\n"]}, {"name": "test.test_regression.Regression.test_15_chd2", "status": "errored", "message": "'fit'", "passed": false, "points": ["p08-01.15"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 346, in test_15_chd2\n    myfit = locals()[\"fit\"]\n"]}, {"name": "test.test_regression.Regression.test_16_chd_visualization", "status": "failed", "message": "Expected 'scatter' to have been called.", "passed": false, "points": ["p08-01.16"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 368, in test_16_chd_visualization\n    pltscatter.assert_called()\n", "  File \"/usr/lib/python3.10/unittest/mock.py\", line 888, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_regression.Regression.test_17_chd_prediction", "status": "failed", "message": "False is not true : Could not find variable 'point'!", "passed": false, "points": ["p08-01.17"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part08-e01_regression/test/test_regression.py\", line 381, in test_17_chd_prediction\n    self.assertTrue(\"point\" in locals(), msg=\"Could not find variable 'point'!\")\n"]}]