[{"name": "test.test_file_listing.FileListing.test_called", "status": "failed", "message": "Expected 'open' to have been called.", "passed": false, "points": ["p02-02.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e02_file_listing/test/test_file_listing.py\", line 67, in test_called\n    o.assert_called()\n", "  File \"/usr/lib/python3.10/unittest/mock.py\", line 888, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_file_listing.FileListing.test_content", "status": "passed", "message": "", "passed": true, "points": ["p02-02.1"], "backtrace": []}, {"name": "test.test_file_listing.FileListing.test_names", "status": "failed", "message": "False is not true", "passed": false, "points": ["p02-02.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e02_file_listing/test/test_file_listing.py\", line 53, in test_names\n    self.assertTrue(names.issuperset({'example_figure.py', 'exception_hierarchy.pdf',\n"]}, {"name": "test.test_file_listing.FileListing.test_size", "status": "failed", "message": "0 != 47 : The returned list should contain 47 tuples!", "passed": false, "points": ["p02-02.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e02_file_listing/test/test_file_listing.py\", line 21, in test_size\n    self.assertEqual(len(result), 47, msg=\"The returned list should contain 47 tuples!\")\n"]}]