[{"name": "test.test_file_extensions.FileExtensions.test_calls", "status": "failed", "message": "Expected 'open' to have been called once. Called 0 times.", "passed": false, "points": ["p02-07.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e07_file_extensions/test/test_file_extensions.py\", line 30, in test_calls\n    o.assert_called_once()\n", "  File \"/usr/lib/python3.10/unittest/mock.py\", line 898, in assert_called_once\n    raise AssertionError(msg)\n"]}, {"name": "test.test_file_extensions.FileExtensions.test_first", "status": "failed", "message": "Lists differ: [] != ['test']\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n'test'\n\n- []\n+ ['test'] : There should be exactly one filename without an extension!", "passed": false, "points": ["p02-07.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e07_file_extensions/test/test_file_extensions.py\", line 22, in test_first\n    self.assertEqual(no_extension, [\"test\"],\n"]}, {"name": "test.test_file_extensions.FileExtensions.test_main", "status": "failed", "message": "0 != 1 : You should call function 'file_extensions' from main!", "passed": false, "points": ["p02-07.2"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e07_file_extensions/test/test_file_extensions.py\", line 36, in test_main\n    self.assertEqual(fe.call_count, 1,\n"]}]