[{"name": "test.test_red_green_blue.RedGreenBlue.test_called", "status": "failed", "message": "Expected 'open' to have been called.", "passed": false, "points": ["p02-03.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e03_red_green_blue/test/test_red_green_blue.py\", line 61, in test_called\n    o.assert_called()\n", "  File \"/usr/lib/python3.10/unittest/mock.py\", line 888, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_red_green_blue.RedGreenBlue.test_content", "status": "errored", "message": "list index out of range", "passed": false, "points": ["p02-03.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e03_red_green_blue/test/test_red_green_blue.py\", line 41, in test_content\n    t = result[1].split(\"\\t\")\n"]}, {"name": "test.test_red_green_blue.RedGreenBlue.test_size", "status": "failed", "message": "0 != 753 : Wrong number of strings in the returned list!", "passed": false, "points": ["p02-03.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e03_red_green_blue/test/test_red_green_blue.py\", line 21, in test_size\n    self.assertEqual(len(result), 753, \"Wrong number of strings in the returned list!\")\n"]}]